apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::986946178909:role/eksctl-eksctl-demo-nodegroup-ng-90-NodeInstanceRole-MPj3WKPLbLZn
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::986946178909:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2026-08-02T13:21:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1314"
  uid: dd82f784-0af6-40cc-9bc0-24c62ff91ca8
